
author: "Zach Barrett"
date: last-modified

project:
  type: website

website:
  title: "Zach's Notes"
  description: "This is my website where I put notes for the courses I TA for"
  back-to-top-navigation: true
  favicon: ./favicons/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: docs/electronics-project/Electronics Project.qmd
        text: Electronics Project
      - href: docs/physics-B/Foundation Physics B.qmd
        text: Foundation Physics B

format:
  html:
    theme:
      light: light.scss
      dark: dark.scss
    highlight-style:
      light: flexoki-light.theme
      dark: flexoki-dark.theme
    css: styles.css
    code-copy: true
    smooth-scroll: true
    toc: true
    reference-location: margin
    anchor-sections: true
    include-after-body:
      - annotation-lines.html
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">


