all: dark light

dark:
	typst compile diode-diagram-dark.typ --pages 1 dark-diodepad.svg
	typst compile diode-diagram-dark.typ --pages 2 dark-style1.svg
	typst compile diode-diagram-dark.typ --pages 2 dark-style2.svg

light: 
	typst compile diode-diagram.typ --pages 1 light-diodepad.svg
	typst compile diode-diagram.typ --pages 2 light-style1.svg
	typst compile diode-diagram.typ --pages 2 light-style2.svg
